In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [3]:
df= pd.read_csv(r'C:\Users\iago_\projeto_10\data\rest_data_us_upd.csv')
df.head()

,id,object_name,address,chain,object_type,number
0,11786,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,False,Cafe,26
1,11787,REILLY'S,100 WORLD WAY 120,False,Restaurant,9
2,11788,STREET CHURROS,6801 HOLLYWOOD BLVD 253,False,Fast Food,20
3,11789,TRINITI ECHO PARK,1814 W SUNSET BLVD,False,Restaurant,22
4,11790,POLLEN,2100 ECHO PARK AVE,False,Restaurant,20

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9651 entries, 0 to 9650
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           9651 non-null   int64
 1   object_name  9651 non-null   str
 2   address      9651 non-null   str
 3   chain        9648 non-null   object
 4   object_type  9651 non-null   str
 5   number       9651 non-null   int64
dtypes: int64(2), object(1), str(3)
memory usage: 870.3+ KB

In [5]:
df['chain'].isna().sum()

np.int64(3)

In [6]:
df['chain'] = df['chain'].fillna('desconhecido')
df['chain'].isna().sum()

np.int64(0)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.head(15)

,id,object_name,address,chain,object_type,number
0,11786,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,False,Cafe,26
1,11787,REILLY'S,100 WORLD WAY 120,False,Restaurant,9
2,11788,STREET CHURROS,6801 HOLLYWOOD BLVD 253,False,Fast Food,20
3,11789,TRINITI ECHO PARK,1814 W SUNSET BLVD,False,Restaurant,22
4,11790,POLLEN,2100 ECHO PARK AVE,False,Restaurant,20
5,11791,THE SPOT GRILL,10004 NATIONAL BLVD,False,Restaurant,14
6,11792,CPK,100 WORLD WAY 126,False,Restaurant,100
7,11793,PHO LALA,3500 W 6TH ST STE 226,False,Restaurant,7
8,11794,ABC DONUTS,3027 N SAN FERNANDO RD UNIT 103,True,Fast Food,1
9,11795,UPSTAIRS,3707 N CAHUENGA BLVD,False,Restaurant,35
10,11796,EL POLLO LOCO,5319 W SUNSET BLVD,True,Restaurant,38
11,11797,POONG NYUN BAKERY,928 S WESTERN AVE STE 109,True,Bakery,17
12,11798,EMC RESTAURANT GROUP LLC,3500 W 6TH ST STE 101,True,Restaurant,133
13,11799,POPULAR DONUTS,3614 W SLAUSON AVE,False,Fast Food,18
14,11800,CUSCATLECA BAKERY,2501 W SUNSET BLVD #A,True,Bakery,26

In [9]:
df['address'].str.split().head()
#O método split  separa cada palavra e cria uma lista com estas palavras

0    [3708, N, EAGLE, ROCK, BLVD]
1          [100, WORLD, WAY, 120]
2    [6801, HOLLYWOOD, BLVD, 253]
3         [1814, W, SUNSET, BLVD]
4         [2100, ECHO, PARK, AVE]
Name: address, dtype: object

In [10]:
df['name_street'] = df['address'].str.split().str[1:].str.join(' ')
df['name_street'].head(10)
#utilizado o metodos split, fatiamento e join para criar a coluna com os nomes das ruas de cada estabelecimento.

0             N EAGLE ROCK BLVD
1                 WORLD WAY 120
2            HOLLYWOOD BLVD 253
3                 W SUNSET BLVD
4                 ECHO PARK AVE
5                 NATIONAL BLVD
6                 WORLD WAY 126
7              W 6TH ST STE 226
8    N SAN FERNANDO RD UNIT 103
9               N CAHUENGA BLVD
Name: name_street, dtype: object

In [11]:
df.head(10)

,id,object_name,address,chain,object_type,number,name_street
0,11786,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,False,Cafe,26,N EAGLE ROCK BLVD
1,11787,REILLY'S,100 WORLD WAY 120,False,Restaurant,9,WORLD WAY 120
2,11788,STREET CHURROS,6801 HOLLYWOOD BLVD 253,False,Fast Food,20,HOLLYWOOD BLVD 253
3,11789,TRINITI ECHO PARK,1814 W SUNSET BLVD,False,Restaurant,22,W SUNSET BLVD
4,11790,POLLEN,2100 ECHO PARK AVE,False,Restaurant,20,ECHO PARK AVE
5,11791,THE SPOT GRILL,10004 NATIONAL BLVD,False,Restaurant,14,NATIONAL BLVD
6,11792,CPK,100 WORLD WAY 126,False,Restaurant,100,WORLD WAY 126
7,11793,PHO LALA,3500 W 6TH ST STE 226,False,Restaurant,7,W 6TH ST STE 226
8,11794,ABC DONUTS,3027 N SAN FERNANDO RD UNIT 103,True,Fast Food,1,N SAN FERNANDO RD UNIT 103
9,11795,UPSTAIRS,3707 N CAHUENGA BLVD,False,Restaurant,35,N CAHUENGA BLVD

In [12]:
tipos_estbl = df.groupby('object_type')['object_name'].count()
tipos_estbl.head(15)

object_type
Bakery         283
Bar            292
Cafe           435
Fast Food     1066
Pizza          320
Restaurant    7255
Name: object_name, dtype: int64

In [13]:
proporção_por_tipo = tipos_estbl / tipos_estbl.sum() * 100

In [14]:
proporção_por_tipo.head(10)

object_type
Bakery         2.932339
Bar            3.025593
Cafe           4.507305
Fast Food     11.045488
Pizza          3.315719
Restaurant    75.173557
Name: object_name, dtype: float64

In [15]:
proporção_por_tipo = proporção_por_tipo.reset_index()
proporção_por_tipo.head()

  object_type  object_name
0      Bakery     2.932339
1         Bar     3.025593
2        Cafe     4.507305
3   Fast Food    11.045488
4       Pizza     3.315719

In [16]:
import plotly.express as px

fig = px.bar(
    proporção_por_tipo,
    x='object_type',
    y='object_name',
    color_discrete_sequence=['#2563EB'],
    width=900,
    height=500
)

fig.update_layout(
    title='Proporção por tipo de estabelecimento',
    xaxis_title='Tipo de estabelecimento',
    yaxis_title='Proporção (%)',
    template='plotly_white',
    showlegend=False
)

fig.show()

In [17]:
df.head()

,id,object_name,address,chain,object_type,number,name_street
0,11786,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,False,Cafe,26,N EAGLE ROCK BLVD
1,11787,REILLY'S,100 WORLD WAY 120,False,Restaurant,9,WORLD WAY 120
2,11788,STREET CHURROS,6801 HOLLYWOOD BLVD 253,False,Fast Food,20,HOLLYWOOD BLVD 253
3,11789,TRINITI ECHO PARK,1814 W SUNSET BLVD,False,Restaurant,22,W SUNSET BLVD
4,11790,POLLEN,2100 ECHO PARK AVE,False,Restaurant,20,ECHO PARK AVE

In [25]:
pp_rede =  df.groupby('chain')['object_type'].count()
pp_rede.head(10)

chain
False           5972
True            3676
desconhecido       3
Name: object_type, dtype: int64

In [30]:
proporção_rede_indp = pp_rede / pp_rede.sum() * 100
proporção_rede_indp.head(10).round()

chain
False           62.0
True            38.0
desconhecido     0.0
Name: object_type, dtype: float64

In [32]:
proporção_rede_indp = proporção_rede_indp.reset_index()

In [41]:
fig = px.bar(
    proporção_rede_indp,
    x='chain',
    y='object_type',
    color_discrete_sequence=['#2563EB'],
    width=900,
    height=500
)

fig.update_layout(
    title='Proporção de estabelecimentos por rede ou independente',
    xaxis_title='tipo de operação',
    yaxis_title='Proporção (%)',
    template='plotly_white',
    showlegend=True 
)

fig.show()

In [42]:
df.head()

,id,object_name,address,chain,object_type,number,name_street
0,11786,HABITAT COFFEE SHOP,3708 N EAGLE ROCK BLVD,False,Cafe,26,N EAGLE ROCK BLVD
1,11787,REILLY'S,100 WORLD WAY 120,False,Restaurant,9,WORLD WAY 120
2,11788,STREET CHURROS,6801 HOLLYWOOD BLVD 253,False,Fast Food,20,HOLLYWOOD BLVD 253
3,11789,TRINITI ECHO PARK,1814 W SUNSET BLVD,False,Restaurant,22,W SUNSET BLVD
4,11790,POLLEN,2100 ECHO PARK AVE,False,Restaurant,20,ECHO PARK AVE

In [44]:
df_tipico_true = df[df['chain'] == True]
df_tipico_true.head()

,id,object_name,address,chain,object_type,number,name_street
8,11794,ABC DONUTS,3027 N SAN FERNANDO RD UNIT 103,True,Fast Food,1,N SAN FERNANDO RD UNIT 103
10,11796,EL POLLO LOCO,5319 W SUNSET BLVD,True,Restaurant,38,W SUNSET BLVD
11,11797,POONG NYUN BAKERY,928 S WESTERN AVE STE 109,True,Bakery,17,S WESTERN AVE STE 109
12,11798,EMC RESTAURANT GROUP LLC,3500 W 6TH ST STE 101,True,Restaurant,133,W 6TH ST STE 101
14,11800,CUSCATLECA BAKERY,2501 W SUNSET BLVD #A,True,Bakery,26,W SUNSET BLVD #A

In [48]:
group_tipico_true = df_tipico_true.groupby('object_type')['chain'].sum()
group_tipico_true.head(10)

object_type
Bakery         283
Bar             77
Cafe           266
Fast Food      605
Pizza          153
Restaurant    2292
Name: chain, dtype: object

In [49]:
group_tipico_true = group_tipico_true.reset_index()

In [55]:
fig = px.bar(
    group_tipico_true,
    x='object_type',
    y='chain',
    color_discrete_sequence=['#2563EB'],
    width=900,
    height=500
    
)

fig.update_layout(
    title='Tipos de estabelecimentos em formato de rede',
    xaxis_title='tipos de estabelecimentos',
    yaxis_title='quantidade',
    template='plotly_white',
    showlegend=True 
)

fig.show()